<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20151115172321 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("CREATE TABLE virtual_domains (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(50) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE virtual_aliases (id INT AUTO_INCREMENT NOT NULL, domain_id INT DEFAULT NULL, source VARCHAR(100) NOT NULL, destination VARCHAR(100) NOT NULL, INDEX IDX_696568F6115F0EE5 (domain_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE virtual_users (id INT AUTO_INCREMENT NOT NULL, domain_id INT DEFAULT NULL, password VARCHAR(106) NOT NULL, email VARCHAR(100) NOT NULL, INDEX IDX_3C68956A115F0EE5 (domain_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("ALTER TABLE virtual_aliases ADD CONSTRAINT FK_696568F6115F0EE5 FOREIGN KEY (domain_id) REFERENCES virtual_domains (id)");
		$this->addSql("ALTER TABLE virtual_users ADD CONSTRAINT FK_3C68956A115F0EE5 FOREIGN KEY (domain_id) REFERENCES virtual_domains (id)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE virtual_aliases DROP FOREIGN KEY FK_696568F6115F0EE5");
		$this->addSql("ALTER TABLE virtual_users DROP FOREIGN KEY FK_3C68956A115F0EE5");
		$this->addSql("DROP TABLE virtual_domains");
		$this->addSql("DROP TABLE virtual_aliases");
		$this->addSql("DROP TABLE virtual_users");
	}
}