<?php
namespace Neos\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20151222135241 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE mailserver_aliases DROP FOREIGN KEY FK_696568F6115F0EE5");
		$this->addSql("DROP INDEX idx_696568f6115f0ee5 ON mailserver_aliases");
		$this->addSql("CREATE INDEX IDX_981EE2A7115F0EE5 ON mailserver_aliases (domain_id)");
		$this->addSql("ALTER TABLE mailserver_aliases ADD CONSTRAINT FK_696568F6115F0EE5 FOREIGN KEY (domain_id) REFERENCES mailserver_domains (id)");
		$this->addSql("ALTER TABLE mailserver_users DROP FOREIGN KEY FK_3C68956A115F0EE5");
		$this->addSql("ALTER TABLE mailserver_users CHANGE email username VARCHAR(128) NOT NULL");
		$this->addSql("DROP INDEX idx_3c68956a115f0ee5 ON mailserver_users");
		$this->addSql("CREATE INDEX IDX_5E6008C3115F0EE5 ON mailserver_users (domain_id)");
		$this->addSql("ALTER TABLE mailserver_users ADD CONSTRAINT FK_3C68956A115F0EE5 FOREIGN KEY (domain_id) REFERENCES mailserver_domains (id)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE kaystrobach_news_domain_model_news CHANGE foreword foreword LONGTEXT NOT NULL COLLATE utf8_unicode_ci, CHANGE content content LONGTEXT NOT NULL COLLATE utf8_unicode_ci");
		$this->addSql("ALTER TABLE mailserver_aliases DROP FOREIGN KEY FK_981EE2A7115F0EE5");
		$this->addSql("DROP INDEX idx_981ee2a7115f0ee5 ON mailserver_aliases");
		$this->addSql("CREATE INDEX IDX_696568F6115F0EE5 ON mailserver_aliases (domain_id)");
		$this->addSql("ALTER TABLE mailserver_aliases ADD CONSTRAINT FK_981EE2A7115F0EE5 FOREIGN KEY (domain_id) REFERENCES mailserver_domains (id)");
		$this->addSql("ALTER TABLE mailserver_users DROP FOREIGN KEY FK_5E6008C3115F0EE5");
		$this->addSql("ALTER TABLE mailserver_users CHANGE username email VARCHAR(100) NOT NULL COLLATE utf8_unicode_ci");
		$this->addSql("DROP INDEX idx_5e6008c3115f0ee5 ON mailserver_users");
		$this->addSql("CREATE INDEX IDX_3C68956A115F0EE5 ON mailserver_users (domain_id)");
		$this->addSql("ALTER TABLE mailserver_users ADD CONSTRAINT FK_5E6008C3115F0EE5 FOREIGN KEY (domain_id) REFERENCES mailserver_domains (id)");
	}
}