<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20151222133435 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("ALTER TABLE virtual_aliases DROP FOREIGN KEY FK_696568F6115F0EE5");
		$this->addSql("ALTER TABLE virtual_users DROP FOREIGN KEY FK_3C68956A115F0EE5");
		$this->addSql("ALTER TABLE virtual_domains RENAME mailserver_domains;");
		$this->addSql("ALTER TABLE virtual_aliases RENAME mailserver_aliases;");
		$this->addSql("ALTER TABLE virtual_users RENAME mailserver_users;");
		$this->addSql("ALTER TABLE mailserver_aliases ADD CONSTRAINT FK_696568F6115F0EE5 FOREIGN KEY (domain_id) REFERENCES mailserver_domains (id)");
		$this->addSql("ALTER TABLE mailserver_users ADD CONSTRAINT FK_3C68956A115F0EE5 FOREIGN KEY (domain_id) REFERENCES mailserver_domains (id)");

	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

	}
}